### PR TITLE
Bug fix: randomize wallpaper

### PR DESCRIPTION
**Pull request by linsyking**
This works for me

### CODE REVIEW

**Comment by catsout** [comment]
Could you give me log(`kquitapp5 plasmashell && kstart5 plasmashell &> plasma.log`) on this pr?

**Comment by linsyking** [comment]
> Could you give me log(`kquitapp5 plasmashell && kstart5 plasmashell &> plasma.log`) on this pr? Need to wait for the wallpaper changed

```
Omitting both --window and --windowclass arguments is not recommended
kf.plasma.quick: Applet preload policy set to 1
trying to show an empty dialog
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:150:13: QML TextArea: Binding loop detected for property "implicitWidth"
file:///usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/ui/main.qml:56:5: QML MouseArea: Cannot anchor to an item that isn't a parent or sibling.
file:///usr/share/plasma/plasmoids/org.kde.plasma.systemmonitor/contents/ui/main.qml:54: TypeError: Cannot read property 'length' of undefined
qml: load backend: backend/Scene.qml
kf.kio.core: Malformed JSON protocol file for protocol: "trash" , number of the ExtraNames fields should match the number of ExtraTypes fields
kf.kirigami: Units.devicePixelRatio is deprecated (since 5.86 ): This returns 1 when using Qt HiDPI scaling.
file:///usr/share/ksysguard/sensorfaces/org.kde.ksysguard.piechart/contents/ui/FullRepresentation.qml:34:1: QML FullRepresentation: Binding loop detected for property "implicitHeight"
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
INFO  miniaudio-wrapper.hpp:116: sound device inited
INFO  WPPkgFs.cpp:22: pkg version: PKGV0002
qt.core.qabstractitemmodel.checkindex: Index QModelIndex(-1,-1,0x0,QObject(0x0)) is not valid (expected valid)
qt.core.qabstractitemmodel.checkindex: Index QModelIndex(-1,-1,0x0,QObject(0x0)) is not valid (expected valid)
qml: scan folder: file:///run/media/linsy/Data/SteamLibrary/steamapps/common/wallpaper_engine/projects/myprojects, found 0 subdir
qml: scan folder: file:///run/media/linsy/Data/SteamLibrary/steamapps/workshop/content/431960, found 22 subdir
qml: show the first: file:///run/media/linsy/Data/SteamLibrary/steamapps/workshop/content/431960/1139304621
qml: scan folder: file:///run/media/linsy/Data/SteamLibrary/steamapps/common/wallpaper_engine/projects/defaultprojects, found 20 subdir
qml: show the first: file:///run/media/linsy/Data/SteamLibrary/steamapps/common/wallpaper_engine/projects/defaultprojects/arsenal
Plasma Shell startup completed
file:///usr/share/plasma/plasmoids/org.kde.plasma.panelspacer/contents/ui/main.qml:53:5: Unable to assign [undefined] to QQuickGridLayout*
Loading Calendar plugin HolidaysEventsPlugin(0x5555a0c9eab0)
trying to show an empty dialog
file:///usr/share/plasma/plasmoids/org.kde.panel/contents/ui/main.qml:30:1: QML DropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
trying to show an empty dialog
qt.core.qabstractitemmodel.checkindex: Index QModelIndex(-1,-1,0x0,QObject(0x0)) is not valid (expected valid)
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:202:17: QML Binding: Not restoring previous value because restoreMode has not been set.
This behavior is deprecated.
You have to import QtQml 2.15 after any QtQuick imports and set
the restoreMode of the binding to fix this warning.
In Qt < 6.0 the default is Binding.RestoreBinding.
In Qt >= 6.0 the default is Binding.RestoreBindingOrValue.

Error: cannot change the containment to AppletsLayout
Both point size and pixel size set. Using pixel size.
file:///usr/share/plasma/plasmoids/org.kde.plasma.digitalclock/contents/ui/Tooltip.qml:66:9: QML GridLayout (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
qt.core.qabstractitemmodel.checkindex: Index QModelIndex(-1,-1,0x0,QObject(0x0)) is not valid (expected valid)
QProcess: Destroyed while process ("/bin/sh") is still running.
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:202:17: QML Binding: Not restoring previous value because restoreMode has not been set.
This behavior is deprecated.
You have to import QtQml 2.15 after any QtQuick imports and set
the restoreMode of the binding to fix this warning.
In Qt < 6.0 the default is Binding.RestoreBinding.
In Qt >= 6.0 the default is Binding.RestoreBindingOrValue.

Error: cannot change the containment to AppletsLayout
Both point size and pixel size set. Using pixel size.
libkcups: CUPS-Get-Printers last error: 1030 未添加目标。
libkcups: Create-Printer-Subscriptions last error: 0 successful-ok
libkcups: Get-Jobs last error: 0 successful-ok
libkcups: Get-Jobs last error: 0 successful-ok
Cyclic dependency detected between "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/global/Globals.qml" and "file:///usr/share/plasma/plasmoids/org.kde.plasma.notifications/contents/ui/NotificationHeader.qml"
qml: ----python helper connected----
libkcups: 0
libkcups: 0
kf.kirigami: Units.devicePixelRatio is deprecated (since 5.86 ): This returns 1 when using Qt HiDPI scaling.
kf.kirigami: Previous message repeats 11 times.
qml: SystemTray ItemLoader: Invalid state, cannot determine source!
file:///usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml:30:1: QML MouseArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
file:///usr/share/plasma/plasmoids/org.kde.plasma.notes/contents/ui/main.qml:202:17: QML Binding: Not restoring previous value because restoreMode has not been set.
This behavior is deprecated.
You have to import QtQml 2.15 after any QtQuick imports and set
the restoreMode of the binding to fix this warning.
In Qt < 6.0 the default is Binding.RestoreBinding.
In Qt >= 6.0 the default is Binding.RestoreBindingOrValue.

Error: cannot change the containment to AppletsLayout
Both point size and pixel size set. Using pixel size.
trying to show an empty dialog
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/views/Desktop.qml:146:19: QML Loader: Binding loop detected for property "height"
QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0
qml: filtered, filter: 11111111011111111111111111111111111, from 0 to 0
qml: received timeout result, id: 0
qml: received timeout result, id: 1
qml: received timeout result, id: 2
qml: received timeout result, id: 3
qml: received timeout result, id: 4
qml: received timeout result, id: 5
qml: received timeout result, id: 6
qml: received timeout result, id: 7
qml: received timeout result, id: 8
qml: received timeout result, id: 9
qml: received timeout result, id: 10
qml: received timeout result, id: 11
qml: received timeout result, id: 12
qml: received timeout result, id: 13
qml: received timeout result, id: 14
qml: received timeout result, id: 15
qml: received timeout result, id: 16
qml: received timeout result, id: 17
qml: received timeout result, id: 18
qml: received timeout result, id: 19
qml: received timeout result, id: 20
qml: received timeout result, id: 21
qml: received timeout result, id: 22
qml: received timeout result, id: 23
qml: received timeout result, id: 24
qml: received timeout result, id: 25
qml: received timeout result, id: 26
qml: received timeout result, id: 27
qml: received timeout result, id: 28
qml: received timeout result, id: 29
qml: received timeout result, id: 30
qml: received timeout result, id: 31
qml: received timeout result, id: 32
qml: received timeout result, id: 33
qml: received timeout result, id: 34
qml: received timeout result, id: 35
qml: received timeout result, id: 36
qml: received timeout result, id: 37
qml: received timeout result, id: 38
qml: received timeout result, id: 39
qml: received timeout result, id: 40
qml: received timeout result, id: 41
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: time out
qml: filtered, filter: 11111111011111111111111111111111111, from 42 to 0
qml: filtered, filter: 11111111011111111111111111111111111, from 42 to 0
qml: scan folder: file:///run/media/linsy/Data/SteamLibrary/steamapps/common/wallpaper_engine/projects/myprojects, found 0 subdir
qml: scan folder: file:///run/media/linsy/Data/SteamLibrary/steamapps/workshop/content/431960, found 22 subdir
qml: show the first: file:///run/media/linsy/Data/SteamLibrary/steamapps/workshop/content/431960/1139304621
qml: scan folder: file:///run/media/linsy/Data/SteamLibrary/steamapps/common/wallpaper_engine/projects/defaultprojects, found 20 subdir
qml: show the first: file:///run/media/linsy/Data/SteamLibrary/steamapps/common/wallpaper_engine/projects/defaultprojects/arsenal
qml: filtered, filter: 11111111011111111111111111111111111, from 42 to 0
qml: filtered, filter: 11111111011111111111111111111111111, from 42 to 21
qml: NotADirectoryError(20, 'Not a directory')
qml: filtered, filter: 11111111011111111111111111111111111, from 42 to 21
qml: load backend: backend/Mpv.qml
Setting property "volume" to QVariant(int, 0)
Setting property "mute" to QVariant(bool, false)
Setting property "keepaspect" to QVariant(bool, true)
Setting property "panscan" to QVariant(int, 0)
INFO  wallpaper.cpp:158: Date cleared
ERROR CBinaryStream.h:64: can't open: /run/media/linsy/Data/SteamLibrary/steamapps/workshop/content/431960/821372791/灵梦.pkg
INFO  wallpaper.cpp:85: load pkg file /run/media/linsy/Data/SteamLibrary/steamapps/workshop/content/431960/821372791/灵梦.pkg failed, fallback to use dir
ERROR wallpaper.cpp:104: Not supported scene type
INFO  wallpaper.cpp:158: Date cleared
INFO  miniaudio-wrapper.hpp:145: uninit sound device
Setting property "volume" to QVariant(int, 5)
Setting property "volume" to QVariant(int, 10)
Setting property "volume" to QVariant(int, 15)
Setting property "volume" to QVariant(int, 20)
Setting property "volume" to QVariant(int, 25)
Setting property "volume" to QVariant(int, 30)
Setting property "volume" to QVariant(int, 35)
Setting property "volume" to QVariant(int, 40)
Setting property "volume" to QVariant(int, 45)
```
This works for me.

**Comment by catsout** [comment]
Better to refresh by a Timer with `running: true` and `interval: 10000`(10s)

**Comment by linsyking** [comment]
And I find another strange thing: When I change random interval while the program is running, the wallpaper still runs by it's original interval. I need to restart program to make it work.
However, if I use the previous commit(7 days ago), there's no such problem.

**Comment by catsout** [comment]
@linsyking 
Use a new startup timer to avoid this

**Comment by linsyking** [comment]
> @linsyking Use a new startup timer to avoid this

ok

**Comment by catsout** [comment]
Please put the timer into WallpaperListModel block  
And remove the id

**Comment by linsyking** [comment]
> @linsyking Use a new startup timer to avoid this

I have changed the code.
Another (small) problem: when wallpaper changes, the volume will be set to the maximum for a short time.

**Comment by linsyking** [comment]
OK.

**Comment by catsout** [comment]
> the volume will be set to the maximum for a short time  
Just open a new issue

**Comment by catsout** [comment]
Thanks for your help

**Pull request merged**
