### PR TITLE
Add openSUSE dependencies to readme

### PR DESCRIPTION
**Pull request by LuisArtDavila**

### CODE REVIEW

**Comment by cglmrfreeman** [comment]
As I also stated in the commit, was this been verified on a clean install? https://github.com/catsout/wallpaper-engine-kde-plugin/issues/203 lists several dependencies that aren't listed here. Also what makes the pacman repo required?

**Comment by LuisArtDavila** [comment]
> As I also stated in the commit, was this been verified on a clean install? #203 lists several dependencies that aren't listed here. Also what makes the pacman repo required?

No, these were not verified with a clean installation but you're more than welcome to amend any changes as needed to my list!

As for your inquiry about Packman; when I did `zypper info gstreamer-plugins-libav` it showed me that it was from the Packman repository, hence the comment. However it does seem that the same package is apart of the official repositories as well. I'm not sure what the differences between the two are.

**Comment by cglmrfreeman** [comment]
I'll spin up a fresh tumbleweed and see if any alterations/additions need to be made. However, I don't actually own Wallpaper Engine, so I will just test the build.

**Comment by yigekuyou** [comment]
I feel this is incomplete ， hard to build on osc

**Pull request merged**
