### PR TITLE
Fixing Scene Segfault

### LINKED ISSUE #35: Scene wallpaper segfault stacktrace
**Describe the bug**
I could retrieve a stack trace from the segfault of some scenes, but I could not figure out why it happens. I tried to use gdb but no luck with it. I could not find the scene that made my plasma shell segfault, I someone has a known segfaulting scene I am willing to test it more to find out why it crash.

**Kde version**
- Kde: 5.22-1
- Qt: 5.15.2
- OS: Arch

**Stack trace**
```
Application: Plasma (plasmashell), signal: Segmentation fault

[KCrash Handler]
#4  0x00007f34cad4d756 in wallpaper::FrameTimer::Stop() () at /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/libWallpaperEngineKde.so
#5  0x00007f34cad4a0ca in SceneViewer::~SceneViewer() () at /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/libWallpaperEngineKde.so
#6  0x00007f34cad40529 in QQmlPrivate::QQmlElement<SceneViewer>::~QQmlElement() () at /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/libWallpaperEngineKde.so
#7  0x00007f34dfb04b7e in QObjectPrivate::deleteChildren() () at /usr/lib/libQt5Core.so.5
#8  0x00007f34dfb0f915 in QObject::~QObject() () at /usr/lib/libQt5Core.so.5
#9  0x00007f34e1694357 in  () at /usr/lib/libQt5Quick.so.5
#10 0x00007f34dfb072a0 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#11 0x00007f34e07aed62 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007f34dfada3aa in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#13 0x00007f34dfadd4a9 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib/libQt5Core.so.5
#14 0x00007f34dfb339a4 in  () at /usr/lib/libQt5Core.so.5
#15 0x00007f34dde4e10c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#16 0x00007f34ddea1b99 in  () at /usr/lib/libglib-2.0.so.0
#17 0x00007f34dde4b871 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#18 0x00007f34dfb32fd6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#19 0x00007f34dfad8d1c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#20 0x00007f34dfae1284 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#21 0x000055b19723721a in  ()
#22 0x00007f34df464b25 in __libc_start_main () at /usr/lib/libc.so.6
#23 0x000055b19723734e in  ()
[Inferior 1 (process 12329) detached]
```

### PR DESCRIPTION
**Pull request by AnonymusRaccoon**
I fixed the segfault on the Stop method of the FrameTimer. I also fixed some memory issues (valgrind), thoses issues were mostly uninted values and while I was at it, I applied changes proposed by clang-tidy (fixing override/virtual keyword, explicits...).
I also fixed a memory leak.

Fixes #35 

PS: It seems that there is still a segfault, but I don't think it is related to the same part of the code and it is way less frequent. I'm currently debugging it.

### CODE REVIEW

**Comment by catsout** [comment]
Why do you do `Using an instance instead of a unique for the implementation`  
I use pimpl to reduce some header file dependencies.

**Comment by AnonymusRaccoon** [comment]
When I read the code the first time, I did not understand why it was in a unique and used an instance instead because it felt simpler and cleared some doubt I had with a memory issue. Honestly, this could be reverted, it does not really change anything except coding style.

Just for information, why do you want to reduce header dependencies?

**Comment by catsout** [comment]
1. the wallpaper.h is the end header file to be used in viewer  
2. the wallpaper.h depended glad.h before(currently not), which may cause some issues with qt  
3. the wallpaper.h is also store a global filenode(uesd to read pkg file, and need to rewrite this), it will be included in any where needs to read file. Use pimpl to reduce compile time, for quick testing

**Comment by catsout** [comment]
> PS: It seems that there is still a segfault, but I don't think it is related to the same part of the code and it is way less frequent. I'm currently debugging it.

So this segfault may appear when pause the wallpaper or change the wallpaper?

**Comment by AnonymusRaccoon** [comment]
The segfault that this PR fixes occurred on pausing or switching the wallpaper, the other issue that I find is something a segfault, sometime a freeze. It is way less frequent, but I think it also occurs on pause/switch. I'm currently running my plasmashell with gdb to debug it when it occurs, but I have no idea how to reproduce it.

PS: I will revert the commit 210b7ba

**Comment by catsout** [comment]
Looks good to me.

**Comment by catsout** [comment]
@AnonymusRaccoon 
I think the new commit may fix this problem.    
Can you test it?

**Comment by AnonymusRaccoon** [comment]
It does fix the issue. Thanks!

**Pull request merged**
